language: python
python:
  - "3.5"
  - "3.6"
  - "3.7"
# command to install dependencies
install:
  - pip install netCDF4
  - pip install scipy
  - pip install numpy
  - pip install matplotlib

# command to run tests
script:
  - pytest
