language: python
python:
  - "3.5"
  - "3.6"
# command to install dependencies
install:
  # - pip install NetCDFIO
  # - pip install netCDF4
  # - pip install pylab
  - pip install scipy
  - pip install numpy
  - pip install matplotlib

# command to run tests
script:
  - python test.py
